// <auto-generated />
using System;
using FEENALOoFINALE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FEENALOoFINALE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250727202251_AddEquipmentSeedDataWithHigherIds")]
    partial class AddEquipmentSeedDataWithHigherIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FEENALOoFINALE.Models.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<string>("AssignedToUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlertId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingId"));

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BuildingId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            BuildingId = 1,
                            BuildingName = "Petroleum Building"
                        },
                        new
                        {
                            BuildingId = 2,
                            BuildingName = "New Engineering Building"
                        });
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<double?>("AverageWeeklyUsageHours")
                        .HasColumnType("float");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentModelId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedLifespanMonths")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("EquipmentModelId");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("RoomId");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            EquipmentId = 100,
                            AverageWeeklyUsageHours = 25.5,
                            BuildingId = 1,
                            EquipmentModelId = 1,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Classroom projector #1",
                            RoomId = 1,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 101,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #1",
                            RoomId = 1,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 102,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #2",
                            RoomId = 1,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 103,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #3",
                            RoomId = 1,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 104,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #4",
                            RoomId = 1,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 105,
                            AverageWeeklyUsageHours = 20.0,
                            BuildingId = 1,
                            EquipmentModelId = 5,
                            EquipmentTypeId = 3,
                            ExpectedLifespanMonths = 120,
                            InstallationDate = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Lecture podium",
                            RoomId = 1,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 106,
                            AverageWeeklyUsageHours = 25.5,
                            BuildingId = 1,
                            EquipmentModelId = 1,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Classroom projector #1",
                            RoomId = 2,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 107,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #1",
                            RoomId = 2,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 108,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #2",
                            RoomId = 2,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 109,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #3",
                            RoomId = 2,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 110,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #4",
                            RoomId = 2,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 111,
                            AverageWeeklyUsageHours = 20.0,
                            BuildingId = 1,
                            EquipmentModelId = 5,
                            EquipmentTypeId = 3,
                            ExpectedLifespanMonths = 120,
                            InstallationDate = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Lecture podium",
                            RoomId = 2,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 112,
                            AverageWeeklyUsageHours = 25.5,
                            BuildingId = 1,
                            EquipmentModelId = 1,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Classroom projector #1",
                            RoomId = 3,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 113,
                            AverageWeeklyUsageHours = 25.5,
                            BuildingId = 1,
                            EquipmentModelId = 4,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Classroom projector #2",
                            RoomId = 3,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 114,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #1",
                            RoomId = 3,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 115,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #2",
                            RoomId = 3,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 116,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #3",
                            RoomId = 3,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 117,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #4",
                            RoomId = 3,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 118,
                            AverageWeeklyUsageHours = 20.0,
                            BuildingId = 1,
                            EquipmentModelId = 5,
                            EquipmentTypeId = 3,
                            ExpectedLifespanMonths = 120,
                            InstallationDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Lecture podium",
                            RoomId = 3,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 119,
                            AverageWeeklyUsageHours = 25.5,
                            BuildingId = 1,
                            EquipmentModelId = 1,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2024, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Classroom projector #1",
                            RoomId = 4,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 120,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #1",
                            RoomId = 4,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 121,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #2",
                            RoomId = 4,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 122,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #3",
                            RoomId = 4,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 123,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #4",
                            RoomId = 4,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 124,
                            AverageWeeklyUsageHours = 20.0,
                            BuildingId = 1,
                            EquipmentModelId = 5,
                            EquipmentTypeId = 3,
                            ExpectedLifespanMonths = 120,
                            InstallationDate = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Lecture podium",
                            RoomId = 4,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 125,
                            AverageWeeklyUsageHours = 25.5,
                            BuildingId = 1,
                            EquipmentModelId = 1,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Classroom projector #1",
                            RoomId = 5,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 126,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #1",
                            RoomId = 5,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 127,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #2",
                            RoomId = 5,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 128,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #3",
                            RoomId = 5,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 129,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #4",
                            RoomId = 5,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 130,
                            AverageWeeklyUsageHours = 20.0,
                            BuildingId = 1,
                            EquipmentModelId = 5,
                            EquipmentTypeId = 3,
                            ExpectedLifespanMonths = 120,
                            InstallationDate = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Lecture podium",
                            RoomId = 5,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 131,
                            AverageWeeklyUsageHours = 25.5,
                            BuildingId = 1,
                            EquipmentModelId = 1,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Classroom projector #1",
                            RoomId = 6,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 132,
                            AverageWeeklyUsageHours = 25.5,
                            BuildingId = 1,
                            EquipmentModelId = 4,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Classroom projector #2",
                            RoomId = 6,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 133,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #1",
                            RoomId = 6,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 134,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #2",
                            RoomId = 6,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 135,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #3",
                            RoomId = 6,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 136,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #4",
                            RoomId = 6,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 137,
                            AverageWeeklyUsageHours = 20.0,
                            BuildingId = 1,
                            EquipmentModelId = 5,
                            EquipmentTypeId = 3,
                            ExpectedLifespanMonths = 120,
                            InstallationDate = new DateTime(2024, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Lecture podium",
                            RoomId = 6,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 138,
                            AverageWeeklyUsageHours = 25.5,
                            BuildingId = 1,
                            EquipmentModelId = 1,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Classroom projector #1",
                            RoomId = 7,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 139,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #1",
                            RoomId = 7,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 140,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #2",
                            RoomId = 7,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 141,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 1,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #3",
                            RoomId = 7,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 142,
                            AverageWeeklyUsageHours = 20.0,
                            BuildingId = 1,
                            EquipmentModelId = 5,
                            EquipmentTypeId = 3,
                            ExpectedLifespanMonths = 120,
                            InstallationDate = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Lecture podium",
                            RoomId = 7,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 143,
                            AverageWeeklyUsageHours = 25.5,
                            BuildingId = 2,
                            EquipmentModelId = 1,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Classroom projector #1",
                            RoomId = 8,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 144,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 2,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #1",
                            RoomId = 8,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 145,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 2,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #2",
                            RoomId = 8,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 146,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 2,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #3",
                            RoomId = 8,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 147,
                            AverageWeeklyUsageHours = 20.0,
                            BuildingId = 2,
                            EquipmentModelId = 5,
                            EquipmentTypeId = 3,
                            ExpectedLifespanMonths = 120,
                            InstallationDate = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Lecture podium",
                            RoomId = 8,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 148,
                            AverageWeeklyUsageHours = 25.5,
                            BuildingId = 2,
                            EquipmentModelId = 1,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2024, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Classroom projector #1",
                            RoomId = 9,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 149,
                            AverageWeeklyUsageHours = 25.5,
                            BuildingId = 2,
                            EquipmentModelId = 4,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2024, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Classroom projector #2",
                            RoomId = 9,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 150,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 2,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #1",
                            RoomId = 9,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 151,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 2,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #2",
                            RoomId = 9,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 152,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 2,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #3",
                            RoomId = 9,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 153,
                            AverageWeeklyUsageHours = 20.0,
                            BuildingId = 2,
                            EquipmentModelId = 5,
                            EquipmentTypeId = 3,
                            ExpectedLifespanMonths = 120,
                            InstallationDate = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Lecture podium",
                            RoomId = 9,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 154,
                            AverageWeeklyUsageHours = 25.5,
                            BuildingId = 2,
                            EquipmentModelId = 1,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2024, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Classroom projector #1",
                            RoomId = 10,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 155,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 2,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #1",
                            RoomId = 10,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 156,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 2,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #2",
                            RoomId = 10,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 157,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 2,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #3",
                            RoomId = 10,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 158,
                            AverageWeeklyUsageHours = 20.0,
                            BuildingId = 2,
                            EquipmentModelId = 5,
                            EquipmentTypeId = 3,
                            ExpectedLifespanMonths = 120,
                            InstallationDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Lecture podium",
                            RoomId = 10,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 159,
                            AverageWeeklyUsageHours = 25.5,
                            BuildingId = 2,
                            EquipmentModelId = 1,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2024, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Classroom projector #1",
                            RoomId = 11,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 160,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 2,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #1",
                            RoomId = 11,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 161,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 2,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #2",
                            RoomId = 11,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 162,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 2,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #3",
                            RoomId = 11,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 163,
                            AverageWeeklyUsageHours = 20.0,
                            BuildingId = 2,
                            EquipmentModelId = 5,
                            EquipmentTypeId = 3,
                            ExpectedLifespanMonths = 120,
                            InstallationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Lecture podium",
                            RoomId = 11,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 164,
                            AverageWeeklyUsageHours = 25.5,
                            BuildingId = 2,
                            EquipmentModelId = 1,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2024, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Classroom projector #1",
                            RoomId = 12,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 165,
                            AverageWeeklyUsageHours = 25.5,
                            BuildingId = 2,
                            EquipmentModelId = 4,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2024, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Classroom projector #2",
                            RoomId = 12,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 166,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 2,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #1",
                            RoomId = 12,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 167,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 2,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #2",
                            RoomId = 12,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 168,
                            AverageWeeklyUsageHours = 40.0,
                            BuildingId = 2,
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HVAC unit #3",
                            RoomId = 12,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 169,
                            AverageWeeklyUsageHours = 20.0,
                            BuildingId = 2,
                            EquipmentModelId = 5,
                            EquipmentTypeId = 3,
                            ExpectedLifespanMonths = 120,
                            InstallationDate = new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Lecture podium",
                            RoomId = 12,
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 170,
                            AverageWeeklyUsageHours = 0.0,
                            BuildingId = 1,
                            EquipmentModelId = 4,
                            EquipmentTypeId = 1,
                            ExpectedLifespanMonths = 60,
                            InstallationDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Old projector - needs repair",
                            RoomId = 7,
                            Status = 1
                        },
                        new
                        {
                            EquipmentId = 171,
                            AverageWeeklyUsageHours = 0.0,
                            BuildingId = 2,
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ExpectedLifespanMonths = 84,
                            InstallationDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Retired air conditioner - end of life",
                            RoomId = 12,
                            Status = 2
                        });
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.EquipmentModel", b =>
                {
                    b.Property<int>("EquipmentModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentModelId"));

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipmentModelId");

                    b.HasIndex("EquipmentTypeId");

                    b.ToTable("EquipmentModels");

                    b.HasData(
                        new
                        {
                            EquipmentModelId = 1,
                            EquipmentTypeId = 1,
                            ModelName = "Black Dragon lenovo v4 projector"
                        },
                        new
                        {
                            EquipmentModelId = 2,
                            EquipmentTypeId = 2,
                            ModelName = "21D model 6 Hisense air conditioner"
                        },
                        new
                        {
                            EquipmentModelId = 3,
                            EquipmentTypeId = 2,
                            ModelName = "21D model 4 Hisense air conditioner"
                        },
                        new
                        {
                            EquipmentModelId = 4,
                            EquipmentTypeId = 1,
                            ModelName = "2005 Metallic back grey projector"
                        },
                        new
                        {
                            EquipmentModelId = 5,
                            EquipmentTypeId = 3,
                            ModelName = "XX5 Dragon Podium"
                        });
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.EquipmentType", b =>
                {
                    b.Property<int>("EquipmentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentTypeId"));

                    b.Property<string>("EquipmentTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipmentTypeId");

                    b.ToTable("EquipmentTypes");

                    b.HasData(
                        new
                        {
                            EquipmentTypeId = 1,
                            EquipmentTypeName = "Projectors"
                        },
                        new
                        {
                            EquipmentTypeId = 2,
                            EquipmentTypeName = "Air Conditioners"
                        },
                        new
                        {
                            EquipmentTypeId = 3,
                            EquipmentTypeName = "Podiums"
                        });
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.EquipmentUsageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<double>("UsageHours")
                        .HasColumnType("float");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("EquipmentUsageHistories");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.FailurePrediction", b =>
                {
                    b.Property<int>("PredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredictionId"));

                    b.Property<string>("AnalysisNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("int");

                    b.Property<string>("ContributingFactors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PredictedFailureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PredictionId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("FailurePredictions");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.InventoryItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("CompatibleModels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxStockLevel")
                        .HasColumnType("int");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int");

                    b.Property<int>("MinimumStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReorderPoint")
                        .HasColumnType("int");

                    b.Property<int>("ReorderQuantity")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.InventoryStock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockId"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StockId");

                    b.HasIndex("ItemId");

                    b.ToTable("InventoryStocks");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.MaintenanceInventoryLink", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("LogId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("int");

                    b.HasKey("LinkId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LogId");

                    b.ToTable("MaintenanceInventoryLinks");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int?>("AlertId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("DowntimeDuration")
                        .HasColumnType("time");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaintenanceTaskId")
                        .HasColumnType("int");

                    b.Property<int>("MaintenanceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Technician")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.HasIndex("AlertId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("MaintenanceTaskId");

                    b.ToTable("MaintenanceLogs");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.MaintenanceTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<string>("AssignedToUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedFromAlertId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedFromAlertId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("MaintenanceTasks");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomId");

                    b.HasIndex("BuildingId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            BuildingId = 1,
                            RoomName = "PB001"
                        },
                        new
                        {
                            RoomId = 2,
                            BuildingId = 1,
                            RoomName = "PB012"
                        },
                        new
                        {
                            RoomId = 3,
                            BuildingId = 1,
                            RoomName = "PB014"
                        },
                        new
                        {
                            RoomId = 4,
                            BuildingId = 1,
                            RoomName = "PB020"
                        },
                        new
                        {
                            RoomId = 5,
                            BuildingId = 1,
                            RoomName = "PB201"
                        },
                        new
                        {
                            RoomId = 6,
                            BuildingId = 1,
                            RoomName = "PB208"
                        },
                        new
                        {
                            RoomId = 7,
                            BuildingId = 1,
                            RoomName = "PB214"
                        },
                        new
                        {
                            RoomId = 8,
                            BuildingId = 2,
                            RoomName = "NEB-GF"
                        },
                        new
                        {
                            RoomId = 9,
                            BuildingId = 2,
                            RoomName = "NEB-FF1"
                        },
                        new
                        {
                            RoomId = 10,
                            BuildingId = 2,
                            RoomName = "NEB-FF2"
                        },
                        new
                        {
                            RoomId = 11,
                            BuildingId = 2,
                            RoomName = "NEB-SF"
                        },
                        new
                        {
                            RoomId = 12,
                            BuildingId = 2,
                            RoomName = "NEB-TF"
                        });
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.SavedDashboardView", b =>
                {
                    b.Property<int>("ViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViewId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FilterConfig")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ViewId");

                    b.HasIndex("UserId");

                    b.ToTable("SavedDashboardViews");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipmentUsageDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfWeeks")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessingMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("int");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TimetableFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalEquipmentHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SemesterId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.SemesterEquipmentUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoomName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<string>("UsagePatternJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WeeklyUsageHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("float(8)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("SemesterId", "EquipmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_SemesterEquipmentUsage_Semester_Equipment");

                    b.ToTable("SemesterEquipmentUsages");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailVerificationTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.Alert", b =>
                {
                    b.HasOne("FEENALOoFINALE.Models.User", "AssignedTo")
                        .WithMany("AssignedAlerts")
                        .HasForeignKey("AssignedToUserId");

                    b.HasOne("FEENALOoFINALE.Models.Equipment", "Equipment")
                        .WithMany("Alerts")
                        .HasForeignKey("EquipmentId");

                    b.HasOne("FEENALOoFINALE.Models.InventoryItem", "InventoryItem")
                        .WithMany("Alerts")
                        .HasForeignKey("InventoryItemId");

                    b.Navigation("AssignedTo");

                    b.Navigation("Equipment");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.Equipment", b =>
                {
                    b.HasOne("FEENALOoFINALE.Models.Building", "Building")
                        .WithMany("Equipments")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FEENALOoFINALE.Models.EquipmentModel", "EquipmentModel")
                        .WithMany("Equipments")
                        .HasForeignKey("EquipmentModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FEENALOoFINALE.Models.EquipmentType", "EquipmentType")
                        .WithMany("Equipments")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FEENALOoFINALE.Models.Room", "Room")
                        .WithMany("Equipments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("EquipmentModel");

                    b.Navigation("EquipmentType");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.EquipmentModel", b =>
                {
                    b.HasOne("FEENALOoFINALE.Models.EquipmentType", "EquipmentType")
                        .WithMany("EquipmentModels")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.EquipmentUsageHistory", b =>
                {
                    b.HasOne("FEENALOoFINALE.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.FailurePrediction", b =>
                {
                    b.HasOne("FEENALOoFINALE.Models.Equipment", "Equipment")
                        .WithMany("FailurePredictions")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.InventoryStock", b =>
                {
                    b.HasOne("FEENALOoFINALE.Models.InventoryItem", "InventoryItem")
                        .WithMany("InventoryStocks")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.MaintenanceInventoryLink", b =>
                {
                    b.HasOne("FEENALOoFINALE.Models.InventoryItem", "InventoryItem")
                        .WithMany("MaintenanceInventoryLinks")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FEENALOoFINALE.Models.MaintenanceLog", "MaintenanceLog")
                        .WithMany("MaintenanceInventoryLinks")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("MaintenanceLog");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.MaintenanceLog", b =>
                {
                    b.HasOne("FEENALOoFINALE.Models.Alert", "Alert")
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FEENALOoFINALE.Models.Equipment", "Equipment")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FEENALOoFINALE.Models.MaintenanceTask", "Task")
                        .WithMany()
                        .HasForeignKey("MaintenanceTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alert");

                    b.Navigation("Equipment");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.MaintenanceTask", b =>
                {
                    b.HasOne("FEENALOoFINALE.Models.User", "AssignedTo")
                        .WithMany("MaintenanceTasks")
                        .HasForeignKey("AssignedToUserId");

                    b.HasOne("FEENALOoFINALE.Models.Alert", "OriginatingAlert")
                        .WithMany()
                        .HasForeignKey("CreatedFromAlertId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FEENALOoFINALE.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Equipment");

                    b.Navigation("OriginatingAlert");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.Room", b =>
                {
                    b.HasOne("FEENALOoFINALE.Models.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.SavedDashboardView", b =>
                {
                    b.HasOne("FEENALOoFINALE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.Semester", b =>
                {
                    b.HasOne("FEENALOoFINALE.Models.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.SemesterEquipmentUsage", b =>
                {
                    b.HasOne("FEENALOoFINALE.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FEENALOoFINALE.Models.Semester", "Semester")
                        .WithMany("SemesterEquipmentUsages")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FEENALOoFINALE.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FEENALOoFINALE.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FEENALOoFINALE.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FEENALOoFINALE.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.Building", b =>
                {
                    b.Navigation("Equipments");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.Equipment", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("FailurePredictions");

                    b.Navigation("MaintenanceLogs");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.EquipmentModel", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.EquipmentType", b =>
                {
                    b.Navigation("EquipmentModels");

                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.InventoryItem", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("InventoryStocks");

                    b.Navigation("MaintenanceInventoryLinks");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.MaintenanceLog", b =>
                {
                    b.Navigation("MaintenanceInventoryLinks");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.Room", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.Semester", b =>
                {
                    b.Navigation("SemesterEquipmentUsages");
                });

            modelBuilder.Entity("FEENALOoFINALE.Models.User", b =>
                {
                    b.Navigation("AssignedAlerts");

                    b.Navigation("MaintenanceTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
